[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.15'
via_ir = false

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200000
gas_price = 30_000_000_000
block_base_fee_per_gas = 25_000_000_000

block_number = 0
block_timestamp = 1600000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
